# Stage 1: Build the Spring Boot application
FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app

# Clone the Spring Boot project from GitHub
RUN git clone https://github.com/himanshusemwal3/TestAPI.git .

# Build the Spring Boot application
RUN mvn clean install

# Stage 2: Create a lightweight image to run the application
FROM openjdk:latest
WORKDIR /app

# Copy the JAR file from the build stage
COPY --from=build /app/target/TestAPI-0.0.1-SNAPSHOT.jar /app/

# Expose the port
EXPOSE 8080

# Specify the command to run on container startup
CMD ["java", "-jar", "TestAPI-0.0.1-SNAPSHOT.jar"]
